spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gjf
    password: Gjf@123456
    url: jdbc:mysql://10.10.51.225:3306/lt_trade?useUnicode=true&characterEncoding=utf-8
    druid:
      initial-size: 1 #初始化时建立的连接数
      max-active: 5 #最大活跃数
      max-wait: 60000 #等待超时时间
      filter: stat,wall #监控与SQL注入过滤器
      stat-view-servlet: #监控页面
        enabled: true
        login-username: gailt
        login-password: gailt
  redis:
    host: 10.10.51.225
    port: 6379
    password: gjf*#123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  executor:
    core-pool-size: 2
    max-pool-size: 8
    keep-alive-seconds: 300

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-prefix: mybatis-logs
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

rocketmq:
  name-server: 212.64.69.77:9876