spring:
  application:
    name: lt-trade-business
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.68:8848

server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true