server:
  port: 6070

spring:
  application:
    name: lt-trade-task
  main:
      allow-bean-definition-overriding: true

rocketmq:
  name-server: 212.64.69.77:9876
#  name-server: 127.0.0.1:9876
  producer:
    group: TASK-PRODUCER-GROUP

logging:
  level:
    boot: debug