spring:
  application:
    name: lt-trade-tushare
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.68:8848

server:
  port: 6060

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    boot: debug